apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sleep
  name: sleep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  strategy: {}
  template:
    metadata:
      labels:
        app: sleep
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image: ubuntu:18.04
        name: sleep
        command:
          - "sleep"
        args:
          - infinity
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
