apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-demo
  namespace: admission-demo
spec:
  isCA: true
  commonName: "*.admission-demo.svc"
  secretName: admission-demo-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - api
  - api.admission-demo
  - api.admission-demo.svc
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
