apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: sanic-webhook
build:
  tagPolicy:
    envTemplate:
      template: "{{.TAG}}"
  artifacts:
  - image: harshanarayana/admission-demo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command:
              - "./setup.sh"
    manifests:
    - deployment/namespace.yaml
    - deployment/crb.yaml
    - certs/cert.yaml
    - deployment/deployment.yaml
    - deployment/service.yaml
