apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: maglev-admission-webhook
webhooks:
  - name: maglev-admission-webhook.k8s.io
    clientConfig:
      service:
        name: maglev-admission-webhook
        namespace: default
        path: "/mutating"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1Ea3hNakV3TkRJd09Gb1hEVEk1TURreE1ERXdOREl3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlR3CnBYeUF5aEZweGh2Y3NpVVorVEl6MHIvbE51MDdMWEVxUEZJR0NXZUlDTHBOelluOENuM2hNY3JPSzJJOHVFZEsKaEVqY0FBbUZFU3NkOGgyTlR0d3FlRUJoN1FiZkV6Q1ZjM29QdlBDa2RRdTJ6MklEMmFEL05iWUYyL2J3QVRZbgpPeWJOVGlGVlBMdlVHcjl5WGRrYnRGSlJ4eFlDd2ZmVFlEWWQ5MHVyekRQU3dxWDRoem5sOHhwSGxUdFhtNU84ClJWMHNuN01NU0MrWG1Sc1BBcGJzaEdQTzF1eWNPRkE0Z3pzSWF1eGhyWldTQXRFT0k3QWdHV3l4WDhvcEtwRFkKN2dpZVpyVEhablA0dzExVU5yUzI4TGZWQWNTL2h5WjhnWHFoZVhhNzgrclNrZ2JCSVd2TE91YU92MkE1WTZldQp6NVRJNjJlRHRSeFh6MmpvS0w4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDVkZsMHVYMlJucnpvYW1IZXExU0F5Q0FMaWxqSElBdmswbjhWTnQvSFlQUkdsT1JCVApoaDJ6SzdsZ1VFRGpIRWo5VFl5UFdlRURaaHY3Qi9obGkxQngzeTIzc1F1dEVVK2U4dmlTcGFyZzNKeHVFazZHCmdFd1NyUnhrRXJ0UWhIMGhxTzh0aGRtVFVpbmEwKzhWUXA5QjllazRxS0hUVUsrSWViUFgwejV6SG9YMjQxckMKb21TQjltR0xuU0RsVjQzT3F3VjlaWjlQQVl0alRiZi8yVjlyWng5a3VkMzUwZENnUTltZ1hXV0hJL0FVc2lTKwpEdG81S0c2UUQzM0tvaHdYc2VsdytSc1VmYlJaWXJ2c0hRalJjRXh1OGh2aDRQVU8xTDRDZXJYcEVQc0sxTG52CkZla1R1VXhoMDE0RkY2RDRlWVRGYzBnNE9jSm5NUmFmWWsrNgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "apps"
        apiVersions:
          - "*"
        resources:
          - "deployments"
          - "statefulsets"
          - "daemonsets"
    failurePolicy: Fail
