apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: admission-demo
spec:
  ports:
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
  selector:
    apps: admission-demo