apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-demo
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: ##CABUNDLE##
      service:
        name: api
        namespace: admission-demo
        path: /disallow-host-mounts
        port: 443
    name: disallow-host-mounts.mks.admission
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 5
    rules:
      - apiGroups:
          - "apps"
        apiVersions:
          - "v1"
        operations:
          - CREATE
        resources:
          - deployments
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: ignore-admission
          operator: DoesNotExist