apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-demo
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: ##CABUNDLE##
      service:
        name: api
        namespace: admission-demo
        path: /audit
        port: 443
    name: audit-all.mks.admission
    sideEffects: None
    failurePolicy: Ignore
    matchPolicy: Equivalent
    timeoutSeconds: 5
    rules:
      - apiGroups:
          - ""
          - "apps"
        apiVersions:
          - "v1"
          - "v1"
        operations:
          - CREATE
        resources:
          - pods
          - deployments
        scope: "Namespaced"
  - admissionReviewVersions:
        - v1
    clientConfig:
      caBundle: ##CABUNDLE##
      service:
        name: api
        namespace: admission-demo
        path: /resource-enforce
        port: 443
    name: resource-enforce.mks.admission
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 5
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        operations:
          - CREATE
        resources:
          - pods
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: ignore-admission
          operator: DoesNotExist
  - admissionReviewVersions:
        - v1
    clientConfig:
      caBundle: ##CABUNDLE##
      service:
        name: api
        namespace: admission-demo
        path: /deny-exec
        port: 443
    name: deny-exec.mks.admission
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    timeoutSeconds: 5
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        operations:
          - CONNECT
        resources:
          - pods/*
        scope: "Namespaced"
