apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ app_name }}
  name: {{ app_name }}
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6543
  selector:
    app: {{ app_name }}
  sessionAffinity: None
  type: ClusterIP
