apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ app_name }}
webhooks:
  - name: {{ app_name }}.k8s.io
    clientConfig:
      service:
        name: {{ app_name }}
        namespace: default
        path: "/validating"
      caBundle: {{ ca_bundle }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - "apps"
        apiVersions:
          - "*"
        resources:
          - "deployments"
          - "statefulsets"
          - "daemonsets"
    failurePolicy: Fail
  - name: {{ app_name }}.k8s.io
    clientConfig:
      service:
        name: {{ app_name }}
        namespace: default
        path: "/validate-delete"
      caBundle: {{ ca_bundle }}
    rules:
      - operations:
          - DELETE
        apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - "pods"
    failurePolicy: Fail
